name: backend

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macOS-latest
        raku-version:
          - 'latest'
          # - '2019.11'
    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: agrammon_test
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}

#      - name: Show environment infos
#        run: |
#          psql --version
#          raku -v
#          which raku
#          pwd
#          ls -al
#          ls -al $HOME
#          env

      - name: Load test database
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: agrammon_test
          PGPASSFILE: ./dev/pgpass
          AGRAMMON_DUMP: ./t/test-data/agrammon_test.dump.sql
        run: |
          chmod 0600 $PGPASSFILE
          ls -l $PGPASSFILE
          cat $PGPASSFILE
          psql -U postgres -h localhost -c "CREATE USER agrammon PASSWORD 'agrammonATwork'" > /dev/null
          psql -U postgres -h localhost -c "CREATE GROUP agrammon_user USER agrammon"       > /dev/null
          psql -U postgres -h localhost -c "CREATE EXTENSION pgcrypto" agrammon_test        > /dev/null
          psql -U postgres -h localhost --file=$AGRAMMON_DUMP $POSTGRES_DB                  > /dev/null

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: $GITHUB_WORKSPACE/.raku
          key: ${{ runner.os }}-deps

      - name: Install dependencies
        run: |
          sudo apt install libxml2
          mkdir -p $GITHUB_WORKSPACE/.raku
          ls -al $GITHUB_WORKSPACE/.raku
          # zef --install-to=#inst$GITHUB_WORKSPACE/.raku --debug --deps-only --/test --test-depends install .
          zef --install-to=inst#$GITHUB_WORKSPACE/.raku --debug --/test install Spreadsheet::XLSX
          RAKULIB=inst#$GITHUB_WORKSPACE/.raku zef locate Spreadsheet::XLSX

      - name: Run tests
        run: |
          RAKULIB=inst#$GITHUB_WORKSPACE/.raku prove6 -l -v t/config.t t/datasource-db.t
